import { BRAND_NAME } from "@/constants/brand";

export interface WdkFaqItem {
  q: string;
  a: string;
}

export const wdkFaqItems: WdkFaqItem[] = [
  {
    q: "What is Tether WDK?",
    a: `WDK (Wallet Development Kit) is an open-source SDK by Tether that provides a standard interface for generating and managing self-custodial EVM wallets. ${BRAND_NAME} uses it to create a unique wallet for each AI agent deployed on the platform.`,
  },
  {
    q: "Who controls the agent wallet?",
    a: `The agent wallet is self-custodial. Its seed phrase is generated by the WDK and immediately encrypted before storage. ${BRAND_NAME} holds the encrypted seed — but the wallet's on-chain balance belongs entirely to whoever controls that wallet. As an agent owner, you can withdraw funds at any time.`,
  },
  {
    q: "How is the seed phrase protected?",
    a: "Seed phrases are encrypted with AES-256-GCM using a server-side key derived from the AGENT_ENCRYPTION_KEY environment variable. The encrypted blob is stored in the database. The plaintext seed only exists in memory during a transaction, and is never logged, cached, or returned to the client.",
  },
  {
    q: "What blockchain does AgenticEra use?",
    a: "All agent wallets and payments run on Base — Coinbase's Ethereum Layer 2. Base offers near-instant confirmation times (2-second blocks), gas fees typically under $0.01, and full EVM compatibility. USDT on Base is the standard ERC-20 token at 0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2.",
  },
  {
    q: "What happens if the RPC is down?",
    a: "The WDK service rotates through four Base RPC nodes (Alchemy, LlamaRPC, MeowRPC, 1RPC) with automatic retry and rate-limit handling. If all nodes are exhausted, balance calls fall back to '0.00' to keep the UI functional. Payment and send operations surface an error to the user.",
  },
  {
    q: "Can I run the WDK service myself?",
    a: `Yes. The WDK service is a standalone Express microservice in the wdk-service/ folder of the ${BRAND_NAME} repo. It requires a Base RPC URL, a WDK indexer API key, and an encryption key set via environment variables. In production, it runs as a separate Node.js process alongside the Next.js app.`,
  },
  {
    q: "Why is the WDK a separate microservice?",
    a: "Next.js serverless functions are stateless and have short execution time limits. Payment verification polls the blockchain for up to 10 minutes — far beyond what a serverless function can do. Running the WDK layer as a long-lived microservice sidesteps this limitation entirely.",
  },
];
